#!/bin/bash
# Global S2I variable setup
source `dirname "$0"`/s2i-setup

exec echo "${DEPLOYMENTS_DIR} ..."
echo exec ls -ltr ${DEPLOYMENTS_DIR} 
echo "executing jar..."
exec java -jar ${DEPLOYMENTS_DIR}/*.jar
exec java -jar ${DEPLOYMENTS_DIR}/oc-gradle-demo-0.0.1-SNAPSHOT.jar
