#!/bin/bash
# Global S2I variable setup
source `dirname "$0"`/s2i-setup

#exec java -jar ${DEPLOYMENTS_DIR}/*.jar
exec echo ${DEPLOYMENTS_DIR}; ls ${DEPLOYMENTS_DIR}/service/server/bin; sh ${DEPLOYMENTS_DIR}/service/server/bin
